config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [ :create, :destroy ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Error page
  get "/error_no_urls", to: "urls#error_no_urls", as: "error_no_urls"
  get "/error_no_access", to: "urls#error_no_access", as: "error_no_access"

  # Custom Routes
  get "/myurls", to: "urls#my_urls", as: "my_urls"
  get "/myurls/:short_url", to: "urls#show_visits", as: "show_visits_by_short_url"
  get "/:short_url", to: "urls#redirect_to_target"
  get "/visits/:short_url", to: "urls#show_visits", as: "show_visits"
  get "/generate/:short_url", to: "urls#show", as: "generate"



  # Defines the root path route ("/")
  root "urls#new"
end

app/models/url.rb
require "nokogiri"
require "open-uri"

class Url < ApplicationRecord
  has_many :visits, dependent: :destroy

  # Unique ID Length determines the number of characters in the Short URL path
  UNIQUE_ID_LENGTH = 8

  # Callbacks
  before_validation :sanitize_target_url
  before_create :generate_short_url, :fetch_title_from_target_url

  # Validation to ensure the target URL is in the correct format, user uuid is present
  validates :target_url, presence: true, format: { with: URI.regexp(%w[http https]), message: "must be a valid URL" }
  validates :user_uuid, presence: true

  private

  # Method to generate unique short URL path
  def generate_short_url
    loop do
      # Generate a random unique short code based on Unique Id Length
      short_url_path = SecureRandom.base58(UNIQUE_ID_LENGTH)
      self.short_url = short_url_path
      if !Url.exists?(short_url: self.short_url)
        break
      end
    end
  end

  # Method to fetch title form the target URL
  def fetch_title_from_target_url
    begin
      doc = Nokogiri::HTML(URI.parse(target_url).open)
      self.title = doc.title if doc
    rescue OpenURI::HTTPError => e
      Rails.logger.error "HTTP error fetching title from URL: #{e.message}"
      self.title = "Unknown Title"
    rescue => e
      Rails.logger.error "Failed to fetch title from URL: #{e.message}"
      self.title = "Unknown Title"
    end
  end

  # Method to sanitize target_url before validation
  def sanitize_target_url
    return if target_url.blank?

    begin
      # Remove leading or trailing whitespaces from URL
      stripped_url = target_url.strip

      # Parse URL to ensure its a valid URI object
      uri = URI.parse(stripped_url)

      # Check if URL has a http or https scheme; if not, add "http://" by default
      unless uri.scheme
        uri = URI.parse("http://#{stripped_url}")
      end

      # Check if URI object is a valid HTTP/ HTTPS and if the hostname is valid
      if (uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)) && uri.host.include?(".")
        # Reconstruct URL as a string
        self.target_url = uri.to_s
      else
        # set to nil so validation fails
        self.target_url = nil
      end
    rescue URI::InvalidURIError
      # IF parsing fails, set target_url to nil so validation will fail
      self.target_url = nil
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ edit update destroy ]

  # Lists all URLs belonging to the current user
  def index
    user_uuid = cookies[:user_uuid]
    @urls = Url.where(user_uuid: user_uuid)
  end

  # Displays the details of a shorten URL
  def show
    @url = Url.find_by(short_url: params[:short_url])

    if @url
      @full_short_url = full_short_url(@url.short_url)
      render :show
      return
    end
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  # Initializes a new URL object for creation
  def new
    @url = Url.new
  end

  # Shows the user's URL and redirects to the visits page of the most recent URL
  def my_urls
    user_uuid = cookies[:user_uuid]

    if user_uuid.present?
      @urls = Url.where(user_uuid: user_uuid).order(created_at: :desc)

      if @urls.present?
        redirect_to show_visits_by_short_url_path(@urls.first.short_url)
      else
        redirect_to error_no_urls_path
      end
    else
      redirect_to error_no_urls_path
    end
  end

  # Redirects to the target URL when accessed via the short URL
  def redirect_to_target
    short_url_param = params[:short_url]
    url = Url.find_by(short_url: short_url_param)

    if url
      visit = url.visits.new(ip_address: request.remote_ip)

      if visit.save
        redirect_to url.target_url, allow_other_host: true
      else
        Rails.logger.error "Failed to save visit: #{visit.errors.full_messages.join(", ")}"
        redirect_to url.target_url, allow_other_host: true
      end

    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end

  # Displays visit details for a specific URL
  def show_visits
    short_url_param = params[:short_url]
    @url = Url.find_by(short_url: short_url_param)

    if @url && @url.user_uuid == cookies[:user_uuid]
      @urls = Url.where(user_uuid: cookies[:user_uuid]).order(created_at: :desc)
      @visits = @url.visits
      @full_short_url = full_short_url(@url.short_url)

      @urls.each do |url|
        url.define_singleton_method(:full_short_url) do
          base = ENV["SHORT_URL_BASE"] || Rails.application.routes.default_url_options[:host]
          "#{base}/#{url.short_url}"
        end
      end
      render "show_visits"
    else
      redirect_to error_no_access_path
    end
  end

  # Creates a new short URL and saves it to the database
  def create
    user_uuid = cookies[:user_uuid] || generate_user_uuid
    @url = Url.new(url_params.merge(user_uuid: user_uuid))
    respond_to do |format|
      if @url.save
        format.html { redirect_to generate_url(@url.short_url), notice: "Url was successfully created." }
        format.json { render json: { target_url: @url.target_url, short_url: full_short_url(@url.short_url), title: @url.title }, status: :created }
      else
        flash.now[:alert] = "Failed to shorten the URL. Please check the URL and try again."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

   # Updates an existing URL record
   def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: "Url was successfully updated." }
        format.json { render json: { target_url: @url.target_url, short_url: full_short_url(@url.short_url), title: @url.title }, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
   end

  # Deletes a URL record from the database
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Generates a UUID for the user and stores it in a cookie
  def generate_user_uuid
    uuid = SecureRandom.uuid
    cookies[:user_uuid]={
      value: uuid,
      expires: 1.year.from_now,
      httponly: true
    }
  end

  # Finds the URL record based on the provided ID
  def set_url
    @url = Url.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def url_params
    params.require(:url).permit(:target_url, :short_url, :title)
  end

  # Generates the full short URL with base path
  def full_short_url(path)
    base = ENV["SHORT_URL_BASE"] || request.base_url
    "#{base}/#{path}"
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_with(model: url, class: "contents") do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :target_url %>
    <%= form.text_field :target_url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :short_url %>
    <%= form.text_field :short_url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Target url:</strong>
    <%= url.target_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Short url:</strong>
    <%= url.short_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= url.title %>
  </p>

</div>

app/views/urls/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing url</h1>

  <%= render "form", url: @url %>

  <%= link_to "Show this url", @url, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to urls", urls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/urls/error_no_access.html.erb
<div class="flex flex-col justify-evenly items-center h-auto w-auto rounded-lg px-8 pt-6 pb-8 mb-4 border-4 border-dashed mt-10 space-y-5 text-center">
  <p class="text-xl lg:text-4xl text-bold text-white">You don't have permission to view this URL's stats.</p>
  <p class="text-xl lg:text-4xl text-bold text-white">Create your own short URL now!</p>
  <%= link_to "Create a New Short URL", root_path, class: "bg-primary hover:opacity-60 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-1/2 text-sm lg:text-base" %>
</div>

app/views/urls/error_no_urls.html.erb
<div class="flex flex-col justify-evenly items-center h-auto w-auto rounded-lg px-8 pt-6 pb-8 mb-4 border-4 border-dashed mt-10 space-y-5 text-center">
  <p class="text-xl lg:text-4xl text-bold text-white">You don't have any short URLs.</p>
  <p class="text-xl lg:text-4xl text-bold text-white">Go make one!</p>
  <%= link_to "Create a New Short URL", root_path, class: "bg-primary hover:opacity-60 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-1/2 text-sm lg:text-base" %>
</div>

app/views/urls/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Urls" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Urls</h1>
    <%= link_to "New url", new_url_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="urls" class="min-w-full">
    <% @urls.each do |url| %>
      <%= render url %>
      <p>
        <%= link_to "Show this url", url, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/urls/new.html.erb
<div class="flex flex-col xl:w-3/4 w-full mx-auto h-full items-center justify-start mt-10">
  <div class=" flex lg:flex-row flex-col lg:h-2/3 h-auto rounded-lg px-8 pt-6 pb-8 mb-4 border-4 border-dashed justify-center">
    <div class="flex flex-col lg:w-1/2 w-full max-h-full justify-center">
      <h1 class="text-6xl lg:text-8xl font-bold mb-10 text-center text-white">MiniURL</h1>
      <p class="text-xl mb-6 text-center text-white mx-3">
        Enter the URL you want to shorten and click "Shorten URL."
      </p>
    </div>
    <%= form_with model: @url, local: true, class: "lg:w-1/2 w-full lg:ml-4 flex flex-col justify-center space-y-4" do |form| %>
      <div>
        <%= form.label :target_url, "Enter URL to shorten", class: "block text-white text-sm font-bold mb-4" %>
        <%= form.text_field :target_url, placeholder: "https://example.com", class: "shadow appearance-none border rounded py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline w-full" %>
        <% if flash[:alert] %>
          <span class="text-xs text-red-600">
            <%= flash[:alert] %>
          </span>
        <% end %>
      </div>
      
      <div>
        <%= form.submit "Shorten URL", class: "w-full bg-primary hover:opacity-60 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-1/2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/urls/show.html.erb
<div class="flex flex-col xl:w-3/4 w-full mx-auto h-full items-center justify-start mt-10">
  <div class=" h-auto w-full rounded-lg px-8 pt-6 pb-8 mb-4 flex lg:flex-row flex-col border-4 border-dashed justify-center">
    <div class="flex flex-col lg:w-1/2 w-full justify-center">
      <h1 class="text-6xl lg:text-8xl font-bold mb-10 text-center text-white">MiniURL</h1>
      <p class="text-xl mb-6 text-center text-white mx-3">
        URL shorten successfully!
      </p>
    </div>

    
    <div class="lg:w-1/2 w-full lg:ml-4 flex flex-col justify-center text-white">
      <h2 class="font-bold text-3xl mx-auto mb-6 text-center">Shortened URL Details</h2>
      
      <div class="flex flex-col lg:space-y-4 w-full">

        <div class="flex flex-col mx-auto w-4/5">
          <span class="font-bold mb-2">Title:</span>
          <div class="bg-secondary text-background p-2 rounded border border-gray-300 text-clip whitespace-nowrap max-w-lg">
            <%= @url.title %>
          </div>
        </div>

        <div class="flex flex-col mx-auto w-4/5">
          <span class="font-bold mb-2">Original URL:</span>
          <div class="bg-secondary text-background p-2 rounded border-gray-300 text-clip whitespace-nowrap max-w-lg">
            <%= @url.target_url%>
          </div>
        </div>

        <div class="flex flex-col mx-auto w-4/5">
          <span class="font-bold mb-2">Short URL:</span>
          <div class="bg-secondary text-background p-2 rounded border-gray-300">
            <%= @full_short_url%>
          </div>
        </div>

        <div class="flex flex-row mx-auto w-4/5 justify-evenly">
          <div class="tooltip" data-tip="Visit URL">
            <a class="btn bg-primary text-black" href="<%= @full_short_url %>" target="_blank">
               <%= image_tag("visit-icon.png", class: "h-6 w-6")%>
            </a>
          </div>
          <div class="tooltip" data-tip="Copy URL" data-controller="clipboard">
            <button id="copy-button" class="btn bg-primary text-black" data-clipboard-text="<%= @full_short_url %>" data-clipboard-target="source" data-action="click->clipboard#copy">
              <%= image_tag("copy-icon.png", class: "h-6 w-6")%>
            </button>
          </div>
          <a class="btn bg-primary text-black w-1/2" href="/">Shorten another</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/urls/show_visits.html.erb
<div class="flex flex-col w-full mx-auto h-3/4 items-center justify-start mt-5">
  <h1 class="text-4xl lg:text-6xl text-white text-center mb-2 lg:mb-5">MiniURL Usage Report</h1>
  <div class="flex lg:flex-row flex-col h-full w-full lg:w-4/5 justify-center lg:space-x-7">
    <ul class="menu menu-horizontal lg:order-first order-last bg-secondary rounded-box lg:w-1/2 w-full h-full max-h-full text-black overflow-y-auto overflow-x-hidden">
      <% if @url %>
        <li class="w-full rounded-lg">
          <div class="flex flex-col items-start bg-primary">
            <div class="text-xs whitespace-normal w-full">
              <%= @url.title %>
            </div>
            <div class="text-bold text-lg lg:text-xl">
              <%= @full_short_url %>
            </div>
            <div class="text-xs whitespace-normal w-full">
              <%= @url.target_url %>
            </div>

            <div class="flex flex-row w-full justify-between items-center">
              <div class="flex flex-row space-x-3 w-1/2 justify-start items-center">
                <div class="tooltip" data-tip="Visit URL">
                  <a class="btn btn-xs bg-primary text-black" href="<%= @full_short_url %>" target="_blank">
                    <%= image_tag("visit-icon.png", class: "h-4 w-4")%>
                  </a>
                </div>
                <div class="tooltip" data-tip="Copy URL" data-controller="clipboard">
                  <button id="copy-button" class="btn btn-xs bg-primary text-black" data-clipboard-text="<%= @full_short_url %>" data-clipboard-target="source" data-action="click->clipboard#copy">
                    <%= image_tag("copy-icon.png", class: "h-4 w-4")%> Copy
                  </button>
                </div>
              </div>

              <p class="text-xs">created <%= time_ago_in_words(@url.created_at) %> ago</p>
            </div>
          </div>
        </li>
      <% end %>
      <% @urls.each do |url| %>
      <% next if url == @url %>
        <li class="w-full">
          <a href="/myurls/<%= url.short_url %>" class="flex flex-col items-start hover:bg-slate-300">
            <div class="text-xs whitespace-normal w-full">
              <%= url.title %>
            </div>
            <div class="text-bold text-xl">
              <%= url.full_short_url %>
            </div>
            <div class="text-xs whitespace-normal w-full">
              <%= url.target_url%>
            </div>

            <p class="text-xs text-right w-full">created <%= time_ago_in_words(url.created_at) %> ago</p>
          </a>
        </li>
      <% end %>
    </ul>
    <div class="flex flex-col w-full lg:w-1/2 h-1/2 lg:h-full justify-start lg:order-last order-first">

      <h2 class="text-lg xl:text-2xl text-white my-2 lg:my-5 mx-auto"><%= @full_short_url%></h2>

      <div class="flex w-full mb-2 lg:mb-5">
        <div class="card bg-secondary text-black text-xs lg:text-base rounded-box grid h-10 lg:h-20 flex-grow place-items-center w-1/2">
          <p><strong>Total Visits:</strong> <%= @visits.present? ? @visits.count : 0 %></p>
        </div>
        <div class="divider divider-horizontal"></div>
        <div class="card bg-secondary text-black text-xs lg:text-base rounded-box flex flex-row items-center justify-center h-10 lg:h-20 flex-grow w-1/2">
          <p class="mr-2"><strong>Top Country:</strong></p>
          <p>
            <% top_country = @visits.group(:country).order('count_id DESC').limit(1).count(:id).first %>
            <%= top_country.present? ? top_country[0] : "-" %>
          </p>
        </div>
      </div>

      <div class="overflow-x-auto h-full border border-white rounded-lg mb-2 lg:mb-0">
        <table class="table text-white bg-background ">
          <thead class="sticky top-0 bg-background">
            <tr class="text-white">
              <th>Visit TimeStamp</th>
              <th>City</th>
              <th>Region</th>
              <th>Country</th>
            </tr>
          </thead>
          <tbody>
            <% if @visits.any?%>
              <% @visits.order(created_at: :desc).limit(10).each do |visit| %>
                <tr>
                  <td class="px-2 lg:px-4 py-2"><%= visit.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                  <td class="px-2 lg:px-4 py-2"><%= visit.city %></td>
                  <td class="px-2 lg:px-4 py-2"><%= visit.region %></td>
                  <td class="px-2 lg:px-4 py-2"><%= visit.country %></td>
                </tr>
              <% end %>
            <%else%>
              <tr>
                <td colspan="4" class="text-center items-center lg:h-96 text-xl lg:text-2xl">URL has not been visited</td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      
    </div>
  </div>
</div>